Add spread list and spread map operator support
cloudbees/groovy-cps pull request #116
Opened 2021-11-25 19:57 UTC by sonallux

This PR adds support for spread list `[*x, 1, 2]`, spread map `[*:x, a: 'a']` and spread in arguments `sum(*args, 42)`.

Closes [JENKINS-46163](https://issues.jenkins.io/browse/JENKINS-46163)

2021-12-20 20:02 UTC, sonallux commented
@dwnusbaum and @car-roll friendly ping. This is ready for review.

2021-12-21 05:24 UTC, car-roll commented
@sonallux thanks for the PR! This is probably more under @dwnusbaum 's expertise, but I'm going to take my time and learn what I can going through your PR.

2021-12-21 16:01 UTC, dwnusbaum requested changes
Thanks! I added a few comments. Any time we add support for new Groovy features I am concerned about the security and maintenance implications, but I think this is probably ok.

Can you file a linked PR to `workflow-cps` with a deployed snapshot of this PR?

2021-12-28 08:14 UTC, sonallux commented on lib/src/main/java/com/cloudbees/groovy/cps/impl/FunctionCallBlock.java
> +        List<Object> args = new ArrayList<>();
Ok, I was not aware of that. I have changed to logic a bit to leave the type unchanged.

2021-12-28 08:15 UTC, sonallux commented on lib/src/test/groovy/com/cloudbees/groovy/cps/impl/SpreadListBlockTest.groovy
> +class SpreadListBlockTest extends AbstractGroovyCpsTest {
I have refactored all new tests to plain java test files.

2021-12-28 08:15 UTC, sonallux commented on lib/src/test/groovy/com/cloudbees/groovy/cps/impl/SpreadListBlockTest.groovy
> +    }
Done 👍

2021-12-28 08:17 UTC, sonallux commented on lib/src/test/groovy/com/cloudbees/groovy/cps/impl/SpreadMapBlockTest.groovy
> +    @Test(expected = NullPointerException)
True, it's everywhere with explicit try/catch blocks. I have changed this.

2021-12-28 08:19 UTC, sonallux commented on lib/src/main/java/com/cloudbees/groovy/cps/impl/SpreadList.java
> +        throw new SpreadListEvaluatingException("Cannot spread the list " + value.getClass().getName() + ", value " + value);
Thanks for finding this. I have changed the logic to match the behaviour of real groovy.

2021-12-28 08:38 UTC, sonallux commented
> Thanks! I added a few comments. Any time we add support for new Groovy features I am concerned about the security and maintenance implications, but I think this is probably ok.

@dwnusbaum I have resolved all your comments.

> Can you file a linked PR to `workflow-cps` with a deployed snapshot of this PR?

Sure, did you mean the [workflow-cps-plugin](https://github.com/jenkinsci/workflow-cps-plugin)? I think I also need some advice on how to deploy `groovy-cps` to `repo.jenkins-ci.org`. Is it just `mvn deploy` to deploy a version?

2022-01-29 14:16 UTC, ajschmidt8 commented
Any updates on this PR?

2022-02-03 21:34 UTC, sonallux commented
@dwnusbaum friendly ping. I have resolved all your comments.

2022-08-23 20:14 UTC, jycr commented
Any news?

2022-10-21 13:38 UTC, jgsqware commented
up pinging this too :D

2022-10-27 19:50 UTC, dwnusbaum commented
I was able to look into this a bit this week. I filed https://github.com/cloudbees/groovy-cps/pull/123 with some improvements (mostly minor things). I am closing this PR in favor of that one.

2022-10-27 19:50 UTC, closed without merging